# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKXNmMp4zwUL-YbtQq3HnR112kNDWH09
"""

import streamlit as st
import fitz  # PyMuPDF
from PIL import Image
import io

# Set up page config
st.set_page_config(page_title="Codex Form Auto-Filler", layout="wide")

def process_pdf(input_pdf, data_mapping):
    doc = fitz.open(stream=input_pdf, filetype="pdf")

    # Iterate through all pages to find and fill labels
    for page_index in range(len(doc)):
        page = doc[page_index]

        for label, value in data_mapping.items():
            # search_for returns a list of rectangles where the text is found
            text_instances = page.search_for(label)

            for inst in text_instances:
                # Logic: Place the answer relative to the label found
                # For this form, we usually place it to the right (x1 + offset)
                # or slightly below depending on the field type.

                # Check if the label is at the very bottom (like page 5 signatures)
                if "Name and Surname:" in label or "CEO Name:" in label:
                    insert_point = fitz.Point(inst.x1 + 10, inst.y1 - 2)
                else:
                    # Default: Place slightly to the right of the label
                    insert_point = fitz.Point(inst.x1 + 10, inst.y1 - 2)

                page.insert_text(insert_point, str(value), fontsize=10, color=(0, 0, 0.8))

    # Save to a bytes buffer
    out_pdf = io.BytesIO()
    doc.save(out_pdf)
    doc.close()
    return out_pdf.getvalue()

# --- UI Layout ---
st.title("📄 Codex Company Profiling Auto-Filler")
st.info("Upload the 'Empty Codex - Company Profiling Form.pdf' to see the auto-fill in action.")

# Sidebar for Master Data Input
st.sidebar.header("Master Data Reference")
master_data = {
    "Company Name": st.sidebar.text_input("Company Name", "Cyberdyne Systems Ltd"),
    "Founded": st.sidebar.text_input("Founded (Date of Incorporation)", "1997-08-29"),
    "Headquarters": st.sidebar.text_input("Headquarters", "123 Tech Plaza, Neo Tokyo"),
    "Industry": st.sidebar.text_input("Industry", "Artificial Intelligence & Robotics"),
    "Motto": st.sidebar.text_input("Company Motto", "The Future is Now"),
    "CEO": st.sidebar.text_input("CEO Name", "John Doe")
}

# Mapping labels from the Codex Form to Master Data
# Includes exact whitespaces and line breaks from source [cite: 91, 93, 95, 97, 99, 187]
field_mapping = {
    "Company Name": master_data["Company Name"],
    "Date of Incorporation": master_data["Founded"],
    "Registered Address/Principal Place": master_data["Headquarters"],
    "Line of Business": master_data["Industry"],
    "Company Motto": master_data["Motto"],
    "CEO Name:": master_data["CEO"],
    "Name and Surname:": master_data["CEO"],
    "Industry:": master_data["Industry"]
}

uploaded_file = st.file_uploader("Choose the PDF form...", type="pdf")

if uploaded_file:
    # Process the PDF
    with st.spinner("Analyzing PDF coordinates and applying data..."):
        processed_pdf_bytes = process_pdf(uploaded_file.read(), field_mapping)

        # Display the resulting PDF
        st.success("Form mapped and filled successfully!")

        # Download Button
        st.download_button(
            label="📥 Download Filled PDF",
            data=processed_pdf_bytes,
            file_name="Filled_Codex_Form.pdf",
            mime="application/pdf"
        )

        # Preview Section (First Page)
        st.subheader("Preview (Page 1)")
        doc_preview = fitz.open(stream=processed_pdf_bytes, filetype="pdf")
        page = doc_preview[0]
        pix = page.get_pixmap(dpi=100)
        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
        st.image(img, use_column_width=True)